### PR TITLE
Add psalm as dev-dependency

### PR DESCRIPTION
**Pull request by boesing**

### CODE REVIEW

**Review by michalbundyra — COMMENTED** [review]
Travis CI configuration should be updated. I think we should add new env var there and run static analysis only once with locked deps.

EDIT: Also, we need to add default psalm configuration file (update .gitattributes as well)

**Review by weierophinney — CHANGES_REQUESTED** [review]
I agree with @michalbundyra - we need to also include the default psalm configuration. You can look in laminas-cli or automatic-releases to see what we've used, and we can add it here.

**Comment by boesing** [comment]
I've added the `psalm.xml.dist` (from automatic-releases).

@michalbundyra There is no need to add psalm to travis as it has to be done in the organziations `.github` repository.

**Comment by michalbundyra** [comment]
@boesing 

> There is no need to add psalm to travis as it has to be done in the organziations .github repository.

we are not using anywhere this shared travis configuration from `.github`. Maybe we should. The problem is that usually we need some custom configuration per repository and it is problematic.

**Comment by boesing** [comment]
> @boesing
> 
> > There is no need to add psalm to travis as it has to be done in the organziations .github repository.
> 
> we are not using anywhere this shared travis configuration from `.github`. Maybe we should. The problem is that usually we need some custom configuration per repository and it is problematic.

Exactly, but we are using it in this repository. So, do you want me to create a full-fledged travis configuration in this PR instead?

**Pull request closed without merging**
